name: Dotnet Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          cache: true
          cache-dependency-path: |
            global.json
            **/*.csproj

      - name: Restore
        run: dotnet restore HackPleasanterApi.sln

      - name: Verify whitespace formatting
        run: dotnet format whitespace HackPleasanterApi.sln --verify-no-changes --no-restore

      - name: Verify code style formatting
        run: dotnet format style HackPleasanterApi.sln --verify-no-changes --no-restore

      - name: Lint
        run: dotnet build HackPleasanterApi.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test HackPleasanterApi.sln --configuration Release --no-restore -m:1 -nodeReuse:false
